import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOSS = ROOT / "moss"
VALID = ROOT / "tests" / "fixtures" / "valid"
INVALID = ROOT / "tests" / "fixtures" / "invalid"


class CliTests(unittest.TestCase):
    def run_cli(self, *args, input_text=None, cwd=ROOT):
        return subprocess.run(
            [str(MOSS), *args],
            cwd=cwd,
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def test_help_prints_commands(self):
        result = self.run_cli("help")

        self.assertEqual(result.returncode, 0)
        self.assertIn("Commands:", result.stdout)
        self.assertIn("run FILE.moss", result.stdout)

    def test_missing_file_is_a_cli_error(self):
        result = self.run_cli("run", "does-not-exist.moss")

        self.assertEqual(result.returncode, 1)
        self.assertIn("file not found", result.stderr)

    def test_show_rust_prints_generated_rust(self):
        result = self.run_cli("show-rust", str(VALID / "hello.moss"))

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("// Generated by Moss", result.stdout)
        self.assertIn("fn main()", result.stdout)

    def test_run_valid_fixtures_match_stdout(self):
        for source_path in sorted(VALID.glob("*.moss")):
            with self.subTest(source=source_path.name):
                stdin_path = source_path.with_suffix(".stdin")
                stdout_path = source_path.with_suffix(".stdout")
                input_text = stdin_path.read_text() if stdin_path.exists() else None

                result = self.run_cli("run", str(source_path), input_text=input_text)

                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(result.stdout, stdout_path.read_text())

    def test_invalid_fixture_stops_before_rust_compiler(self):
        result = self.run_cli("run", str(INVALID / "undefined_bare_word.moss"))

        self.assertEqual(result.returncode, 1)
        self.assertIn('Moss found "hi"', result.stderr)
        self.assertNotIn("error[E", result.stderr)
        self.assertEqual(result.stdout, "")

    def test_build_writes_standalone_binary(self):
        with tempfile.TemporaryDirectory() as tmp:
            result = self.run_cli("build", str(VALID / "hello.moss"), cwd=tmp)
            built = Path(tmp) / "hello"

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue(built.exists())
            self.assertIn("built:", result.stdout)


if __name__ == "__main__":
    unittest.main()
