
// Generated by Moss. Do not edit by hand.

#![allow(unused_imports, dead_code, unused_variables, unused_mut)]

use serde_json::{json, Value};
use std::io::{IsTerminal, Read};

fn moss_str(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Null => String::from(""),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        _ => v.to_string(),
    }
}

fn moss_read_input() -> Value {
    if std::io::stdin().is_terminal() {
        return Value::Null;
    }
    let mut buf = String::new();
    if std::io::stdin().read_to_string(&mut buf).is_err() {
        return Value::Null;
    }
    if buf.trim().is_empty() {
        return Value::Null;
    }
    serde_json::from_str(&buf).unwrap_or(Value::Null)
}

fn main() {
    let input: Value = moss_read_input();
    { let _moss_v: Value = {
        let mut map = serde_json::Map::new();
        map.insert(String::from("protocol"), Value::String(String::from("pgap/1")));
        map.insert(String::from("type"), Value::String(String::from("alert")));
        map.insert(String::from("payload"), {
        let mut map = serde_json::Map::new();
        map.insert(String::from("heading"), Value::String(format!("new {} from {}", moss_str(&input.pointer("/payload/action").cloned().unwrap_or(Value::Null)), moss_str(&input.pointer("/payload/user").cloned().unwrap_or(Value::Null)))));
        map.insert(String::from("original_type"), input.pointer("/type").cloned().unwrap_or(Value::Null));
        map.insert(String::from("score"), input.pointer("/payload/score").cloned().unwrap_or(Value::Null));
        Value::Object(map)
    });
        Value::Object(map)
    }; println!("{}", _moss_v); }
}
