
// Generated by Moss. Do not edit by hand.

#![allow(unused_imports, dead_code, unused_variables)]

use serde_json::{json, Value};

fn moss_str(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Null => String::from(""),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        _ => v.to_string(),
    }
}

fn main() {
    let greeting: Value = Value::String(String::from("hello"));
    let count: Value = json!(3i64);
    let active: Value = json!(true);
    let count: Value = json!(10i64);
    let a_piece_of_text: Value = Value::String(String::from("hello"));
    let a_whole_number: Value = json!(42i64);
    let a_decimal: Value = json!(3.14f64);
    let a_boolean: Value = json!(true);
    let a_missing_value: Value = Value::Null;
    let a_list_of_things: Value = Value::Array(vec![Value::String(String::from("apple")), Value::String(String::from("banana")), Value::String(String::from("cherry"))]);
    let user: Value = {
        let mut map = serde_json::Map::new();
        map.insert(String::from("name"), Value::String(String::from("ada")));
        map.insert(String::from("age"), json!(36i64));
        map.insert(String::from("is_admin"), json!(true));
        Value::Object(map)
    };
    let company: Value = {
        let mut map = serde_json::Map::new();
        map.insert(String::from("name"), Value::String(String::from("Moss Labs")));
        map.insert(String::from("founded"), json!(2024i64));
        map.insert(String::from("address"), {
        let mut map = serde_json::Map::new();
        map.insert(String::from("city"), Value::String(String::from("London")));
        map.insert(String::from("country"), Value::String(String::from("UK")));
        Value::Object(map)
    });
        Value::Object(map)
    };
    let full_greeting: Value = Value::String(format!("hi, {}! you have {} items.", moss_str(&greeting), moss_str(&count)));
    { let _moss_v: Value = Value::String(String::from("this is a simple text message")); println!("{}", _moss_v); }
    { let _moss_v: Value = json!(42i64); println!("{}", _moss_v); }
    { let _moss_v: Value = json!(true); println!("{}", _moss_v); }
    { let _moss_v: Value = a_list_of_things.clone(); println!("{}", _moss_v); }
    { let _moss_v: Value = user.clone(); println!("{}", _moss_v); }
    { let _moss_v: Value = {
        let mut map = serde_json::Map::new();
        map.insert(String::from("type"), Value::String(String::from("example")));
        map.insert(String::from("message"), full_greeting.clone());
        map.insert(String::from("details"), {
        let mut map = serde_json::Map::new();
        map.insert(String::from("status"), Value::String(String::from("ok")));
        map.insert(String::from("count"), count.clone());
        Value::Object(map)
    });
        Value::Object(map)
    }; println!("{}", _moss_v); }
}
